// <auto-generated />
using System;
using ChallengeAlternativo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChallengeAlternativo.Migrations
{
    [DbContext(typeof(GeographicIconsDbContext))]
    [Migration("20220524210326_MigrationAlternative")]
    partial class MigrationAlternative
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChallengeAlternativo.Models.City", b =>
                {
                    b.Property<int?>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<int?>("ContinentId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("ContinentId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ChallengeAlternativo.Models.Continent", b =>
                {
                    b.Property<int?>("ContinentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContinentId");

                    b.ToTable("Continents");
                });

            modelBuilder.Entity("ChallengeAlternativo.Models.GeographicIcon", b =>
                {
                    b.Property<int?>("GeoIconId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GeoIconId");

                    b.HasIndex("CityId");

                    b.ToTable("GeographicIcons");
                });

            modelBuilder.Entity("ChallengeAlternativo.Models.City", b =>
                {
                    b.HasOne("ChallengeAlternativo.Models.Continent", null)
                        .WithMany("Cities")
                        .HasForeignKey("ContinentId");
                });

            modelBuilder.Entity("ChallengeAlternativo.Models.GeographicIcon", b =>
                {
                    b.HasOne("ChallengeAlternativo.Models.City", "City")
                        .WithMany("GeographicIcon")
                        .HasForeignKey("CityId");
                });
#pragma warning restore 612, 618
        }
    }
}
